# Generated by Django 5.0.6 on 2024-05-14 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_options_alter_menu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='BookingDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
